import { trpc } from "@/lib/trpc";
import { useState } from "react";

type Status = "draft" | "published" | "archived";

export function TestimonialManager({ token }: { token: string }) {
  const [status, setStatus] = useState<Status>("published");
  const [quote, setQuote] = useState(""); const [authorName, setAuthorName] = useState(""); const [authorTitle, setAuthorTitle] = useState(""); const [company, setCompany] = useState(""); const [mediaId, setMediaId] = useState<string>("");
  const utils = trpc.useUtils();
  const testimonials = trpc.admin.testimonials.useQuery({ token, status });
  const media = trpc.admin.mediaAssets.useQuery({ token });
  const refresh = () => { testimonials.refetch(); utils.testimonials.list.invalidate(); };
  const create = trpc.admin.createTestimonial.useMutation({ onSuccess: () => { setQuote(""); setAuthorName(""); setAuthorTitle(""); setCompany(""); setMediaId(""); setStatus("draft"); refresh(); } });
  const update = trpc.admin.updateTestimonial.useMutation({ onSuccess: refresh });
  const reorder = trpc.admin.reorderTestimonials.useMutation({ onSuccess: refresh });
  const publish = trpc.admin.publishTestimonial.useMutation({ onSuccess: refresh }); const unpublish = trpc.admin.unpublishTestimonial.useMutation({ onSuccess: refresh }); const archive = trpc.admin.archiveTestimonial.useMutation({ onSuccess: refresh }); const restore = trpc.admin.restoreTestimonial.useMutation({ onSuccess: refresh });
  const mediaOptions = (media.data ?? []).filter((asset) => asset.status !== "archived" && asset.mediaType === "image");
  return <section><div className="mb-6"><h2 className="text-white font-semibold text-lg">Testimonials</h2><p className="text-gray-500 text-sm mt-1">Publish only genuine, approved customer feedback. New entries always begin as drafts.</p></div>
    <form onSubmit={(e) => { e.preventDefault(); create.mutate({ token, quote, authorName, authorTitle: authorTitle || undefined, company: company || undefined, mediaId: mediaId ? Number(mediaId) : null }); }} className="mb-7 rounded-xl border border-gray-800 bg-gray-900 p-5 grid gap-3"><label className="text-xs text-gray-400">Approved customer quote<textarea required minLength={20} value={quote} onChange={e => setQuote(e.target.value)} rows={4} className="mt-1 w-full rounded border border-gray-700 bg-gray-800 p-3 text-sm text-white" /></label><div className="grid md:grid-cols-3 gap-3"><label className="text-xs text-gray-400">Name<input required value={authorName} onChange={e => setAuthorName(e.target.value)} className="mt-1 w-full rounded border border-gray-700 bg-gray-800 p-2 text-sm text-white" /></label><label className="text-xs text-gray-400">Title<input value={authorTitle} onChange={e => setAuthorTitle(e.target.value)} className="mt-1 w-full rounded border border-gray-700 bg-gray-800 p-2 text-sm text-white" /></label><label className="text-xs text-gray-400">Company<input value={company} onChange={e => setCompany(e.target.value)} className="mt-1 w-full rounded border border-gray-700 bg-gray-800 p-2 text-sm text-white" /></label></div><label className="text-xs text-gray-400">Optional logo or photo from Media Library<select value={mediaId} onChange={e => setMediaId(e.target.value)} className="mt-1 w-full rounded border border-gray-700 bg-gray-800 p-2 text-sm text-white"><option value="">No image</option>{mediaOptions.map(asset => <option key={asset.id} value={asset.id}>{asset.title || asset.originalFilename}</option>)}</select></label><button disabled={create.isPending} className="justify-self-start rounded-lg px-4 py-2 text-sm font-semibold text-white" style={{ background: "#7dbe31" }}>{create.isPending ? "Saving…" : "Save as draft"}</button></form>
    <div className="flex gap-2 mb-4">{(["published", "draft", "archived"] as const).map(value => <button key={value} onClick={() => setStatus(value)} className="rounded-lg px-4 py-2 text-sm font-semibold" style={status === value ? { background: "#1260ae", color: "white" } : { color: "#9ca3af" }}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div>
    <div className="space-y-3">{testimonials.isLoading ? <p className="text-gray-500">Loading testimonials…</p> : !testimonials.data?.length ? <p className="rounded-xl border border-gray-800 p-6 text-gray-500">No {status} testimonials.</p> : testimonials.data.map((item, index, items) => <TestimonialCard key={item.id} item={item} mediaOptions={mediaOptions} onSave={(data) => update.mutate({ token, id: item.id, ...data })} onMove={(direction) => { const ordered = [...items]; const target = index + direction; if (target < 0 || target >= ordered.length) return; [ordered[index], ordered[target]] = [ordered[target], ordered[index]]; reorder.mutate({ token, ids: ordered.map(entry => entry.id) }); }} onPublish={() => publish.mutate({ token, id: item.id })} onUnpublish={() => unpublish.mutate({ token, id: item.id })} onArchive={() => archive.mutate({ token, id: item.id })} onRestore={() => restore.mutate({ token, id: item.id })} disableUp={index === 0} disableDown={index === items.length - 1} />)}</div>
  </section>;
}

function TestimonialCard({ item, mediaOptions, onSave, onMove, onPublish, onUnpublish, onArchive, onRestore, disableUp, disableDown }: { item: any; mediaOptions: any[]; onSave: (data: any) => void; onMove: (direction: -1 | 1) => void; onPublish: () => void; onUnpublish: () => void; onArchive: () => void; onRestore: () => void; disableUp: boolean; disableDown: boolean }) {
  const [editing, setEditing] = useState(false); const [quote, setQuote] = useState(item.quote); const [authorName, setAuthorName] = useState(item.authorName); const [authorTitle, setAuthorTitle] = useState(item.authorTitle || ""); const [company, setCompany] = useState(item.company || ""); const [mediaId, setMediaId] = useState(item.mediaId ? String(item.mediaId) : "");
  return <article className="rounded-xl border border-gray-800 bg-gray-900 p-5">{editing ? <div className="space-y-3"><textarea value={quote} onChange={e => setQuote(e.target.value)} rows={5} className="w-full rounded border border-gray-700 bg-gray-800 p-3 text-sm text-white" /><div className="grid md:grid-cols-3 gap-2"><input value={authorName} onChange={e => setAuthorName(e.target.value)} className="rounded border border-gray-700 bg-gray-800 p-2 text-sm text-white" /><input value={authorTitle} onChange={e => setAuthorTitle(e.target.value)} placeholder="Title" className="rounded border border-gray-700 bg-gray-800 p-2 text-sm text-white" /><input value={company} onChange={e => setCompany(e.target.value)} placeholder="Company" className="rounded border border-gray-700 bg-gray-800 p-2 text-sm text-white" /></div><select value={mediaId} onChange={e => setMediaId(e.target.value)} className="w-full rounded border border-gray-700 bg-gray-800 p-2 text-sm text-white"><option value="">No image</option>{mediaOptions.map(asset => <option key={asset.id} value={asset.id}>{asset.title || asset.originalFilename}</option>)}</select><button onClick={() => { onSave({ quote, authorName, authorTitle: authorTitle || null, company: company || null, mediaId: mediaId ? Number(mediaId) : null }); setEditing(false); }} className="rounded px-3 py-1.5 text-xs font-semibold text-white" style={{ background: "#1260ae" }}>Save changes</button></div> : <><blockquote className="text-gray-200 leading-relaxed">“{item.quote}”</blockquote><div className="mt-4 text-sm"><strong className="text-white">{item.authorName}</strong><span className="text-gray-400">{item.authorTitle ? ` · ${item.authorTitle}` : ""}{item.company ? ` · ${item.company}` : ""}</span></div></>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={() => setEditing(value => !value)} className="rounded bg-gray-800 px-3 py-1.5 text-xs text-gray-200">{editing ? "Cancel" : "Edit"}</button><button onClick={() => onMove(-1)} disabled={disableUp} className="rounded bg-gray-800 px-3 py-1.5 text-xs text-gray-300 disabled:opacity-40">Move ↑</button><button onClick={() => onMove(1)} disabled={disableDown} className="rounded bg-gray-800 px-3 py-1.5 text-xs text-gray-300 disabled:opacity-40">Move ↓</button>{item.status === "draft" && <button onClick={onPublish} className="rounded px-3 py-1.5 text-xs font-semibold text-white" style={{ background: "#7dbe31" }}>Publish</button>}{item.status === "published" && <button onClick={onUnpublish} className="rounded bg-gray-800 px-3 py-1.5 text-xs text-gray-200">Unpublish</button>}{item.status === "archived" ? <button onClick={onRestore} className="rounded px-3 py-1.5 text-xs text-white" style={{ background: "#1260ae" }}>Restore draft</button> : <button onClick={onArchive} className="rounded bg-gray-800 px-3 py-1.5 text-xs text-gray-300">Archive</button>}</div></article>;
}
